%% =====================================================================
%  Analyze_Mechanism_PNAS_Subpanel.m
%
%  PNAS-style subpanel
%  Mechanism analysis:
%  Signal Enhancement vs Noise Reduction
%
%  Core definitions:
%    Distance contribution  > 0  = signal enhancement
%    -Variance contribution > 0  = noise reduction
%
%  Statistics:
%    One-sample t-test, right tail, against 0
%
%  Style:
%    1. Standalone PNAS subpanel.
%    2. Remove the large title.
%    3. Arial
%    4. Suitable for subsequent assembly in Affinity.
%    5. Export vector PDF and 600 dpi PNG/TIFF.
%% =====================================================================

clear; clc; close all;

%% =====================================================================
%% A. Basic configuration
%% =====================================================================

DATA_PARENT_DIRECTORY = ...
    figure_input('fig2');

target_sessions = {'s1','extra_var','s2','s3','s5'};

group_labels = {'L','L','L','G','G'};

%% =====================================================================
%% A.1 Category definitions
%% =====================================================================

session_T_categories = struct( ...
    's1',{{'T1','T2'}}, ...
    'extra_var',{{'T1','T2'}}, ...
    's2',{{'T1','T2'}}, ...
    's3',{{'T1','T2'}}, ...
    's5',{{'T1','T2','T3','T4'}});

session_U_categories = struct( ...
    's1',{{'U1','U2'}}, ...
    'extra_var',{{'U1','U2'}}, ...
    's2',{{'U1','U2'}}, ...
    's3',{{'U1','U2'}}, ...
    's5',{{'U1','U2','U3','U4'}});

%% =====================================================================
%% A.2 Neuron IDs
%% =====================================================================

session_config = struct();

session_config.s1.trained_ids = ...
    [7;8;9;12;13;14;17;18;19];

session_config.extra_var.trained_ids = ...
    [7;8;9;12;13;14;17;18;19];

session_config.s5.trained_ids = ...
    [7;8;9;12;13;14;17;18;19];

session_config.s2.trained_ids = ...
    [3;11;12;13;21];

session_config.s3.trained_ids = ...
    [10:18];

%% =====================================================================
%% A.3 Post-training window
%% =====================================================================

session_post_indices = struct();

session_post_indices.s1 = [3,4,5,6];
session_post_indices.s2 = [2,3];
session_post_indices.s3 = [2,3];
session_post_indices.s5 = [3,4,5,6];

%% =====================================================================
%% A.4 Data containers
%% =====================================================================

POOL_DIST = struct( ...
    'L',[], ...
    'G',[]);

POOL_VAR_INV = struct( ...
    'L',[], ...
    'G',[]);

%% =====================================================================
%% A.5 PNAS-style settings
%% =====================================================================

FONT_NAME = 'Arial';

FONT_TICK   = 8;
FONT_LABEL  = 9;
FONT_LEGEND = 8;
FONT_STAR   = 10;
FONT_PANEL  = 12;

% ---------------------------------------------------------
% Colors for the two mechanisms
%
% Distance = cool green
% -Variance = warm yellow/orange
% ---------------------------------------------------------

COLOR_DIST = [0.35,0.62,0.28];

COLOR_VAR  = [0.88,0.64,0.18];

% Optional lighter edges
EDGE_DIST = COLOR_DIST * 0.80;
EDGE_VAR  = COLOR_VAR  * 0.80;

%% =====================================================================
%% B. Data processing
%% =====================================================================

fprintf('Processing Data for Mechanism Analysis...\n');

for s_idx = 1:length(target_sessions)

    sess_name = ...
        target_sessions{s_idx};

    current_group = ...
        group_labels{s_idx};

    %% -----------------------------------------------------
    % Find files.
    %% -----------------------------------------------------

    sdi_path = fullfile( ...
        DATA_PARENT_DIRECTORY, ...
        'Results_SDI', ...
        current_group);

    mat_files = dir(fullfile( ...
        sdi_path, ...
        ['SDI_Results_FR_*' sess_name '*.mat']));

    if isempty(mat_files)

        mat_files = dir(fullfile( ...
            sdi_path, ...
            ['SDI_Results_FR_*' sess_name '.mat']));

    end

    file_info = parse_files( ...
        mat_files, ...
        sdi_path, ...
        {sess_name});

    if isempty(file_info)

        fprintf('No files for %s\n',sess_name);
        continue;

    end

    [~,sort_idx] = ...
        sort([file_info.datenum]);

    sorted_files = ...
        file_info(sort_idx);

    n_days = ...
        length(sorted_files);

    T_cats = ...
        session_T_categories.(sess_name);

    U_cats = ...
        session_U_categories.(sess_name);

    %% -----------------------------------------------------
    % Initialize.
    %% -----------------------------------------------------

    day_data_dist_T = struct();
    day_data_dist_U = struct();

    day_data_var_T = struct();
    day_data_var_U = struct();

    all_cats = [T_cats,U_cats];

    %% -----------------------------------------------------
    % Load data for each day.
    %% -----------------------------------------------------

    for day_idx = 1:n_days

        data = load( ...
            sorted_files(day_idx).path, ...
            'SDI_results');

        for cat_idx = 1:length(all_cats)

            cat_name = ...
                all_cats{cat_idx};

            if ~isfield(day_data_dist_T,cat_name)

                day_data_dist_T.(cat_name) = ...
                    nan(1,n_days);

            end

            if ~isfield(day_data_var_T,cat_name)

                day_data_var_T.(cat_name) = ...
                    nan(1,n_days);

            end

            if ~isfield(day_data_dist_U,cat_name)

                day_data_dist_U.(cat_name) = ...
                    nan(1,n_days);

            end

            if ~isfield(day_data_var_U,cat_name)

                day_data_var_U.(cat_name) = ...
                    nan(1,n_days);

            end

            if isfield( ...
                    data.SDI_results, ...
                    cat_name)

                res = ...
                    data.SDI_results.(cat_name);

                if any(strcmp(cat_name,T_cats))

                    day_data_dist_T.(cat_name)(day_idx) = ...
                        res.Mean_Trained_Distance;

                    day_data_var_T.(cat_name)(day_idx) = ...
                        res.Mean_Trained_Variance;

                else

                    day_data_dist_U.(cat_name)(day_idx) = ...
                        res.Mean_Control_Distance;

                    day_data_var_U.(cat_name)(day_idx) = ...
                        res.Mean_Control_Variance;

                end

            end

        end

    end

    %% -----------------------------------------------------
    % Compute DiD.
    %% -----------------------------------------------------

    if ~isfield( ...
            session_post_indices, ...
            sess_name)

        continue;

    end

    post_indices = ...
        session_post_indices.(sess_name);

    for day_idx = post_indices

        if day_idx > n_days
            continue;
        end

        [ ...
            d_T,d_U, ...
            base_dT,base_dU ...
            ] = ...
            calculate_changes( ...
            day_data_dist_T, ...
            T_cats, ...
            U_cats, ...
            day_idx, ...
            day_data_dist_U);

        [ ...
            v_T,v_U, ...
            base_vT,base_vU ...
            ] = ...
            calculate_changes( ...
            day_data_var_T, ...
            T_cats, ...
            U_cats, ...
            day_idx, ...
            day_data_var_U);

        if ...
                ~isnan(d_T) && ...
                ~isnan(d_U) && ...
                ~isnan(v_T) && ...
                ~isnan(v_U) && ...
                abs(base_dT) > eps && ...
                abs(base_dU) > eps && ...
                abs(base_vT) > eps && ...
                abs(base_vU) > eps

            %% Distance
            pct_dist_T = ...
                (d_T/base_dT)*100;

            pct_dist_U = ...
                (d_U/base_dU)*100;

            did_dist = ...
                pct_dist_T - ...
                pct_dist_U;

            %% Variance
            pct_var_T = ...
                (v_T/base_vT)*100;

            pct_var_U = ...
                (v_U/base_vU)*100;

            did_var_raw = ...
                pct_var_T - ...
                pct_var_U;

            % -------------------------------------------------
            % negative variance:
            % variance reduction -> positive contribution
            % -------------------------------------------------

            contribution_var = ...
                -did_var_raw;

            POOL_DIST.(current_group) = ...
                [ ...
                POOL_DIST.(current_group); ...
                did_dist ...
                ];

            POOL_VAR_INV.(current_group) = ...
                [ ...
                POOL_VAR_INV.(current_group); ...
                contribution_var ...
                ];

        end

    end

end

%% =====================================================================
%% C. Statistics
%% =====================================================================

fprintf('\n--- Statistics: one-sample t-test > 0 ---\n');

% =========================================================
% Remove NaNs.
% =========================================================

dist_L = ...
    POOL_DIST.L(~isnan(POOL_DIST.L));

var_L = ...
    POOL_VAR_INV.L(~isnan(POOL_VAR_INV.L));

dist_G = ...
    POOL_DIST.G(~isnan(POOL_DIST.G));

var_G = ...
    POOL_VAR_INV.G(~isnan(POOL_VAR_INV.G));

% =========================================================
% N
% =========================================================

N_L_Dist = numel(dist_L);
N_L_Var  = numel(var_L);

N_G_Dist = numel(dist_G);
N_G_Var  = numel(var_G);

% =========================================================
% One-sided t-test
% =========================================================

p_L_Dist = one_sample_right_ttest(dist_L);
p_L_Var  = one_sample_right_ttest(var_L);

p_G_Dist = one_sample_right_ttest(dist_G);
p_G_Var  = one_sample_right_ttest(var_G);

% =========================================================
% Mean
% =========================================================

Mean_L = [
    mean(dist_L,'omitnan'), ...
    mean(var_L,'omitnan')
    ];

Mean_G = [
    mean(dist_G,'omitnan'), ...
    mean(var_G,'omitnan')
    ];

% =========================================================
% SEM
% =========================================================

SEM_L = [
    safe_sem(dist_L), ...
    safe_sem(var_L)
    ];

SEM_G = [
    safe_sem(dist_G), ...
    safe_sem(var_G)
    ];

fprintf( ...
    'M1 Distance: N=%d, Mean=%.2f%%, p=%.4f\n', ...
    N_L_Dist, ...
    Mean_L(1), ...
    p_L_Dist);

fprintf( ...
    'M1 -Variance: N=%d, Mean=%.2f%%, p=%.4f\n', ...
    N_L_Var, ...
    Mean_L(2), ...
    p_L_Var);

fprintf( ...
    'M2 Distance: N=%d, Mean=%.2f%%, p=%.4f\n', ...
    N_G_Dist, ...
    Mean_G(1), ...
    p_G_Dist);

fprintf( ...
    'M2 -Variance: N=%d, Mean=%.2f%%, p=%.4f\n', ...
    N_G_Var, ...
    Mean_G(2), ...
    p_G_Var);

%% =====================================================================
%% D. PNAS-style subpanel
%% =====================================================================

% =========================================================
% Approximate dimensions of one panel:
% 8.6 cm × 7.0 cm
%
% Match the preceding SDI/SVM subpanel.
% =========================================================

FIG_W_CM = 8.6;
FIG_H_CM = 7.0;

f = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2,2,FIG_W_CM,FIG_H_CM], ...
    'PaperUnits','centimeters', ...
    'PaperPosition',[0,0,FIG_W_CM,FIG_H_CM], ...
    'PaperSize',[FIG_W_CM,FIG_H_CM]);

ax = axes( ...
    'Position',[0.18,0.18,0.76,0.67]);

hold(ax,'on');

%% =====================================================================
%% E. Data matrix
%% =====================================================================

Means = [
    Mean_L;
    Mean_G
    ];

SEMs = [
    SEM_L;
    SEM_G
    ];

%% =====================================================================
%% F. Grouped bars
%% =====================================================================

b = bar( ...
    ax, ...
    Means, ...
    'grouped', ...
    'BarWidth',0.72);

% ---------------------------------------------------------
% Distance
% ---------------------------------------------------------

b(1).FaceColor = COLOR_DIST;
b(1).EdgeColor = EDGE_DIST;
b(1).LineWidth = 0.7;

% ---------------------------------------------------------
% -Variance
% ---------------------------------------------------------

b(2).FaceColor = COLOR_VAR;
b(2).EdgeColor = EDGE_VAR;
b(2).LineWidth = 0.7;

%% =====================================================================
%% G. Error bars
%% =====================================================================

[ngroups,nbars] = size(Means);

x = nan(nbars,ngroups);

for i = 1:nbars

    x(i,:) = ...
        b(i).XEndPoints;

    errorbar( ...
        ax, ...
        x(i,:), ...
        Means(:,i), ...
        SEMs(:,i), ...
        'k', ...
        'LineStyle','none', ...
        'LineWidth',1.0, ...
        'CapSize',5, ...
        'HandleVisibility','off');

end

%% =====================================================================
%% H. Zero line
%% =====================================================================

yline( ...
    ax, ...
    0, ...
    '-', ...
    'Color',[0.35,0.35,0.35], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

%% =====================================================================
%% I. Y limits
%% =====================================================================

upper_values = ...
    Means + SEMs;

lower_values = ...
    Means - SEMs;

global_max = ...
    max(upper_values(:),[],'omitnan');

global_min = ...
    min(lower_values(:),[],'omitnan');

range_val = ...
    max(global_max-global_min,10);

star_space = ...
    0.22 * range_val;

bottom_space = ...
    0.12 * range_val;

y_top = ...
    global_max + star_space;

y_bottom = ...
    min(global_min-bottom_space,-5);

ylim(ax,[y_bottom,y_top]);

%% =====================================================================
%% J. Significance
%% =====================================================================

star_offset = ...
    0.035 * ...
    (y_top-y_bottom);

add_sig_star( ...
    ax, ...
    x(1,1), ...
    Means(1,1)+SEMs(1,1)+star_offset, ...
    p_L_Dist, ...
    FONT_STAR);

add_sig_star( ...
    ax, ...
    x(2,1), ...
    Means(1,2)+SEMs(1,2)+star_offset, ...
    p_L_Var, ...
    FONT_STAR);

add_sig_star( ...
    ax, ...
    x(1,2), ...
    Means(2,1)+SEMs(2,1)+star_offset, ...
    p_G_Dist, ...
    FONT_STAR);

add_sig_star( ...
    ax, ...
    x(2,2), ...
    Means(2,2)+SEMs(2,2)+star_offset, ...
    p_G_Var, ...
    FONT_STAR);

%% =====================================================================
%% K. Axis style
%% =====================================================================

set( ...
    ax, ...
    'XTick',[1 2], ...
    'XTickLabel',{'M1','M2'}, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_TICK, ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'TickLength',[0.02 0.02], ...
    'XColor',[0.08 0.08 0.08], ...
    'YColor',[0.08 0.08 0.08], ...
    'Box','off');

xlim(ax,[0.50 2.50]);

ylabel( ...
    ax, ...
    'Contribution to improvement (%)', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_LABEL, ...
    'FontWeight','normal');

xlabel(ax,'');

grid(ax,'off');

%% =====================================================================
%% L. Legend
%% =====================================================================

lgd = legend( ...
    ax, ...
    [b(1),b(2)], ...
    { ...
    'Distance', ...
    '-Variance' ...
    }, ...
    'Location','northoutside', ...
    'Orientation','horizontal', ...
    'Box','off');

lgd.FontName = FONT_NAME;
lgd.FontSize = FONT_LEGEND;

%% =====================================================================
%% M. Optional panel letter
%% =====================================================================

% If panel letters are added consistently in Affinity,
% this block can be commented out.

annotation( ...
    f, ...
    'textbox', ...
    [0.015,0.92,0.05,0.05], ...
    'String','F', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_PANEL, ...
    'FontWeight','bold', ...
    'LineStyle','none', ...
    'Margin',0);

%% =====================================================================
%% N. Export
%% =====================================================================

exportgraphics( ...
    f, ...
    'Mechanism_PNAS_Subpanel.pdf', ...
    'ContentType','vector');

exportgraphics( ...
    f, ...
    'Mechanism_PNAS_Subpanel.png', ...
    'Resolution',600);

exportgraphics( ...
    f, ...
    'Mechanism_PNAS_Subpanel.tif', ...
    'Resolution',600);

fprintf('\nSaved:\n');
fprintf('Mechanism_PNAS_Subpanel.pdf\n');
fprintf('Mechanism_PNAS_Subpanel.png\n');
fprintf('Mechanism_PNAS_Subpanel.tif\n');

%% =====================================================================
%% Helper: significance star
%% =====================================================================

function add_sig_star( ...
    ax, ...
    x_pos, ...
    y_pos, ...
    p, ...
    font_size)

    if isnan(p)
        return;
    end

    if p < 0.001

        txt = '***';

    elseif p < 0.01

        txt = '**';

    elseif p < 0.05

        txt = '*';

    else

        % -------------------------------------------------
        % PNAS-style main figures do not necessarily need n.s. labels.
        % To show them, replace the empty string with 'n.s.'.
        % -------------------------------------------------

        txt = '';

    end

    if ~isempty(txt)

        text( ...
            ax, ...
            x_pos, ...
            y_pos, ...
            txt, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontName','Arial', ...
            'FontSize',font_size, ...
            'FontWeight','bold', ...
            'Interpreter','none');

    end

end

%% =====================================================================
%% Helper: changes
%% =====================================================================

function [ ...
    mean_change_T, ...
    mean_change_U, ...
    mean_baseline_T, ...
    mean_baseline_U ...
    ] = ...
    calculate_changes( ...
    day_data_T, ...
    T_cats, ...
    U_cats, ...
    day_idx, ...
    day_data_U)

    if nargin < 5
        day_data_U = day_data_T;
    end

    changes_T = [];
    changes_U = [];

    baseline_T = [];
    baseline_U = [];

    for i = 1:length(T_cats)

        cat_name = ...
            T_cats{i};

        if isfield( ...
                day_data_T, ...
                cat_name)

            val_post = ...
                day_data_T.(cat_name)(day_idx);

            val_base = ...
                day_data_T.(cat_name)(1);

            if ~isnan(val_post) && ...
                    ~isnan(val_base)

                change = ...
                    val_post - ...
                    val_base;

                changes_T = ...
                    [changes_T;change];

                baseline_T = ...
                    [baseline_T;val_base];

            end

        end

    end

    for i = 1:length(U_cats)

        cat_name = ...
            U_cats{i};

        if isfield( ...
                day_data_U, ...
                cat_name)

            val_post = ...
                day_data_U.(cat_name)(day_idx);

            val_base = ...
                day_data_U.(cat_name)(1);

            if ~isnan(val_post) && ...
                    ~isnan(val_base)

                change = ...
                    val_post - ...
                    val_base;

                changes_U = ...
                    [changes_U;change];

                baseline_U = ...
                    [baseline_U;val_base];

            end

        end

    end

    mean_change_T = ...
        mean(changes_T,'omitnan');

    mean_change_U = ...
        mean(changes_U,'omitnan');

    mean_baseline_T = ...
        mean(baseline_T,'omitnan');

    mean_baseline_U = ...
        mean(baseline_U,'omitnan');

end

%% =====================================================================
%% Helper: file parser
%% =====================================================================

function file_info = ...
    parse_files( ...
    mat_files, ...
    directory, ...
    sessions_in_group)

    file_info = struct( ...
        'name',{}, ...
        'path',{}, ...
        'session',{}, ...
        'datenum',{});

    for f_idx = 1:numel(mat_files)

        fileName = ...
            mat_files(f_idx).name;

        session_match = ...
            regexp( ...
            fileName, ...
            's(\d+)', ...
            'tokens');

        if isempty(session_match)
            continue;
        end

        session_name = ...
            sprintf( ...
            's%d', ...
            str2double( ...
            session_match{1}{1}));

        if ~ismember( ...
                session_name, ...
                sessions_in_group)

            continue;

        end

        date_match = ...
            regexp( ...
            fileName, ...
            '(\d{6})\.mat$', ...
            'tokens');

        if isempty(date_match)
            continue;
        end

        date_str = ...
            date_match{1}{1};

        year = ...
            2000 + ...
            str2double(date_str(5:6));

        month = ...
            str2double(date_str(1:2));

        day = ...
            str2double(date_str(3:4));

        file_info(end+1).name = ...
            fileName;

        file_info(end).path = ...
            fullfile( ...
            directory, ...
            fileName);

        file_info(end).session = ...
            session_name;

        file_info(end).datenum = ...
            datenum( ...
            year, ...
            month, ...
            day);

    end

end

%% =====================================================================
%% Helper: one-sample right-tailed t-test
%% =====================================================================

function p = ...
    one_sample_right_ttest(x)

    x = x(~isnan(x));

    if numel(x) < 2

        p = NaN;
        return;

    end

    [~,p] = ...
        ttest( ...
        x, ...
        0, ...
        'Tail','right');

end

%% =====================================================================
%% Helper: SEM
%% =====================================================================

function s = safe_sem(x)

    x = x(~isnan(x));

    if isempty(x)

        s = NaN;

    elseif numel(x) == 1

        s = 0;

    else

        s = ...
            std(x,0) / ...
            sqrt(numel(x));

    end

end