%% =====================================================================
%  var_viz_PNAS_final_clean.m
%
%  Trained Day 1 vs Trained Day N
%
%  ANALYSIS
%  ---------------------------------------------------------------------
%  1. Load Day 1 / Day N
%  2. Extract trained and control responses
%  3. Fit PCA independently for each day
%  4. Project trained/control responses
%  5. Compute condition centroids / covariances
%  6. Align Day N to Day 1 using CONTROL centroids
%       - no scaling
%       - no reflection
%  7. Quantify:
%       - centroid distance
%       - within-condition RMS radius
%       - distance / radius
%
%
%  VISUALIZATION
%  ---------------------------------------------------------------------
%  A. Use one common scalar normalization from control variability.
%
%       x_norm = x / control_scale
%
%  B. Center Day 1 and Day N independently FOR DISPLAY ONLY:
%
%       C_D1_plot = C_D1_norm - mean(C_D1_norm)
%       C_DN_plot = C_DN_norm - mean(C_DN_norm)
%
%  This removes only global translation within each day.
%
%  C. Match mean displayed within-condition radius across days.
%
%       Rref = (R_D1 + R_DN)/2
%
%       Sigma_D1_display =
%           Sigma_D1_norm * (Rref/R_D1)^2
%
%       Sigma_DN_display =
%           Sigma_DN_norm * (Rref/R_DN)^2
%
%  IMPORTANT:
%  This variance matching is DISPLAY ONLY.
%
%  All statistical quantities are computed before display matching.
%
%
%  FINAL FIGURE
%  ---------------------------------------------------------------------
%  - tiledlayout
%  - no legend
%  - no numeric ticks
%  - true xlabel/ylabel/zlabel = D1 / D2 / D3
%  - no manual label Position
%  - no grid
%  - orthographic projection
%  - same limits for both panels
%
%% =====================================================================

clear;
clc;
close all;


%% =====================================================================
%% A. CONFIGURATION
%% =====================================================================

DATA_PARENT_DIRECTORY = ...
    figure_input('historical_fr');

SESSION_NAME = 's7';

CAT_TRAINED = 'T1';
CAT_CONTROL = 'U1';

TARGET_INDICES = [7;8;9;12;13;14;17;18;19];

N_PC = 3;


%% ---------------------------------------------------------------------
% Ellipsoid size
%% ---------------------------------------------------------------------

ELLIPSOID_STD_3D = 0.35;


%% ---------------------------------------------------------------------
% Axis padding
%% ---------------------------------------------------------------------

AXIS_MARGIN = 0.10;


%% ---------------------------------------------------------------------
% Appearance
%% ---------------------------------------------------------------------

ALPHA_3D = 0.52;

ELLIPSOID_RES = 20;

FONT_NAME = 'Helvetica';

FONT_TITLE = 9;
FONT_AXIS  = 8;

AXIS_LINE_WIDTH = 0.55;


%% ---------------------------------------------------------------------
% Figure size
%% ---------------------------------------------------------------------

FIG_W_CM = 17.4;
FIG_H_CM = 7.2;


%% ---------------------------------------------------------------------
% Camera
%% ---------------------------------------------------------------------

VIEW_AZ = 132;
VIEW_EL = 22;


%% ---------------------------------------------------------------------
% Export
%
% When adjusting layout, set these false for much faster iteration.
%% ---------------------------------------------------------------------

EXPORT_PDF = true;
EXPORT_PNG = true;
EXPORT_TIF = true;

RASTER_DPI = 600;


%% =====================================================================
%% B. OUTPUT DIRECTORY
%% =====================================================================

SAVE_DIR = figure_input('figure_exports/fig2D');


if ~exist(SAVE_DIR,'dir')
    mkdir(SAVE_DIR);
end


%% =====================================================================
%% C. FIND DATA FILES
%% =====================================================================

input_dir = fullfile( ...
    DATA_PARENT_DIRECTORY, ...
    SESSION_NAME, ...
    'var');


mat_files = dir(fullfile( ...
    input_dir, ...
    ['FR_' SESSION_NAME '_var_*.mat']));


if isempty(mat_files)

    error( ...
        'No data files found in:\n%s', ...
        input_dir);

end


%% ---------------------------------------------------------------------
% Parse dates
%% ---------------------------------------------------------------------

f_info = struct('datenum',{});


for i = 1:numel(mat_files)

    d_str = regexp( ...
        mat_files(i).name, ...
        '_(\d{6})\.mat$', ...
        'tokens', ...
        'once');


    if isempty(d_str)

        error( ...
            'Cannot parse date from filename: %s', ...
            mat_files(i).name);

    end


    f_info(i).datenum = ...
        datenum( ...
            d_str{1}, ...
            'MMddyy');

end


[~,ord] = ...
    sort([f_info.datenum]);


if numel(ord) < 4

    error( ...
        ['Fewer than four recording files. ' ...
         'Cannot use ord(1) and ord(4).']);

end


%% ---------------------------------------------------------------------
% Select Day 1 / Day N
%% ---------------------------------------------------------------------

file_D1 = ...
    mat_files(ord(1)).name;


file_DN = ...
    mat_files(ord(4)).name;


fprintf('\n============================================\n');
fprintf('Selected files\n');
fprintf('============================================\n');

fprintf('Day 1: %s\n',file_D1);
fprintf('Day N: %s\n',file_DN);


S1 = ...
    load( ...
        fullfile( ...
            input_dir, ...
            file_D1));


SN = ...
    load( ...
        fullfile( ...
            input_dir, ...
            file_DN));


%% =====================================================================
%% D. EXTRACT TRAINED / CONTROL ACTIVITY
%% =====================================================================

DT1_3d = ...
    extract_category_data( ...
        S1, ...
        CAT_TRAINED, ...
        TARGET_INDICES);


DC1_3d = ...
    extract_category_data( ...
        S1, ...
        CAT_CONTROL, ...
        TARGET_INDICES);


DTN_3d = ...
    extract_category_data( ...
        SN, ...
        CAT_TRAINED, ...
        TARGET_INDICES);


DCN_3d = ...
    extract_category_data( ...
        SN, ...
        CAT_CONTROL, ...
        TARGET_INDICES);


%% ---------------------------------------------------------------------
% Dimensions
%% ---------------------------------------------------------------------

nNeuron_D1 = ...
    size(DT1_3d,1);


nNeuron_DN = ...
    size(DTN_3d,1);


nCondition = ...
    size(DT1_3d,2);


fprintf('\n============================================\n');
fprintf('Population dimensions\n');
fprintf('============================================\n');

fprintf('Day 1 neurons: %d\n',nNeuron_D1);
fprintf('Day N neurons: %d\n',nNeuron_DN);
fprintf('Conditions:    %d\n',nCondition);


if size(DTN_3d,2) ~= nCondition

    error( ...
        'Day 1 and Day N have different condition counts.');

end


%% =====================================================================
%% E. FIT PCA INDEPENDENTLY FOR EACH DAY
%% =====================================================================

[mu_D1,sd_D1,coeff_D1,expl_D1] = ...
    fit_day_pca( ...
        DT1_3d, ...
        DC1_3d, ...
        N_PC);


[mu_DN,sd_DN,coeff_DN,expl_DN] = ...
    fit_day_pca( ...
        DTN_3d, ...
        DCN_3d, ...
        N_PC);


fprintf('\n============================================\n');
fprintf('PCA explained variance\n');
fprintf('============================================\n');


fprintf( ...
    'Day 1 top %d PCs: %.2f%%\n', ...
    N_PC, ...
    sum(expl_D1(1:N_PC)));


fprintf( ...
    'Day N top %d PCs: %.2f%%\n', ...
    N_PC, ...
    sum(expl_DN(1:N_PC)));


%% =====================================================================
%% F. PROJECT DATA
%% =====================================================================

[PT1,nVT,nRepT1] = ...
    project_tensor( ...
        DT1_3d, ...
        mu_D1, ...
        sd_D1, ...
        coeff_D1, ...
        N_PC);


[PC1,nVC,nRepC1] = ...
    project_tensor( ...
        DC1_3d, ...
        mu_D1, ...
        sd_D1, ...
        coeff_D1, ...
        N_PC);


[PTN,~,nRepTN] = ...
    project_tensor( ...
        DTN_3d, ...
        mu_DN, ...
        sd_DN, ...
        coeff_DN, ...
        N_PC);


[PCN,~,nRepCN] = ...
    project_tensor( ...
        DCN_3d, ...
        mu_DN, ...
        sd_DN, ...
        coeff_DN, ...
        N_PC);


fprintf('\n');

fprintf( ...
    'Trained repetitions: Day1=%d, DayN=%d\n', ...
    nRepT1, ...
    nRepTN);


fprintf( ...
    'Control repetitions: Day1=%d, DayN=%d\n', ...
    nRepC1, ...
    nRepCN);


%% =====================================================================
%% G. MANIFOLD STATISTICS BEFORE ALIGNMENT
%% =====================================================================

[CenT1_raw,CovT1] = ...
    get_manifold_stats( ...
        PT1, ...
        nVT, ...
        nRepT1);


[CenTN_raw,CovTN_raw] = ...
    get_manifold_stats( ...
        PTN, ...
        nVT, ...
        nRepTN);


[CenC1_raw,CovC1] = ...
    get_manifold_stats( ...
        PC1, ...
        nVC, ...
        nRepC1);


[CenCN_raw,CovCN_raw] = ...
    get_manifold_stats( ...
        PCN, ...
        nVC, ...
        nRepCN);


%% =====================================================================
%% H. ALIGN DAY N TO DAY 1 USING CONTROL CENTROIDS
%% =====================================================================

[~,~,trControl] = ...
    procrustes( ...
        CenC1_raw, ...
        CenCN_raw, ...
        'scaling',false, ...
        'reflection',false);


%% ---------------------------------------------------------------------
% Apply transform to every Day-N trial
%% ---------------------------------------------------------------------

PTN_A = ...
    PTN * trControl.T + ...
    trControl.c(1,:);


PCN_A = ...
    PCN * trControl.T + ...
    trControl.c(1,:);


%% ---------------------------------------------------------------------
% Recompute aligned manifold statistics
%% ---------------------------------------------------------------------

[CenTN_A,CovTN_A] = ...
    get_manifold_stats( ...
        PTN_A, ...
        nVT, ...
        nRepTN);


[CenCN_A,CovCN_A] = ...
    get_manifold_stats( ...
        PCN_A, ...
        nVC, ...
        nRepCN);


%% =====================================================================
%% I. ALIGNMENT CHECK
%% =====================================================================

align_error_before = ...
    mean( ...
        sqrt( ...
            sum( ...
                (CenC1_raw-CenCN_raw).^2, ...
                2)));


align_error_after = ...
    mean( ...
        sqrt( ...
            sum( ...
                (CenC1_raw-CenCN_A).^2, ...
                2)));


fprintf('\n============================================\n');
fprintf('Control alignment\n');
fprintf('============================================\n');


fprintf( ...
    'Before alignment: %.4f\n', ...
    align_error_before);


fprintf( ...
    'After alignment:  %.4f\n', ...
    align_error_after);


%% =====================================================================
%% J. REAL CENTROID DISTANCE
%% =====================================================================

pairDist_D1 = ...
    pdist(CenT1_raw);


pairDist_DN = ...
    pdist(CenTN_A);


meanDist_D1 = ...
    mean(pairDist_D1);


meanDist_DN = ...
    mean(pairDist_DN);


distance_ratio = ...
    meanDist_DN / ...
    max(meanDist_D1,eps);


fprintf('\n============================================\n');
fprintf('Trained centroid separation\n');
fprintf('============================================\n');


fprintf( ...
    'Mean distance Day 1: %.4f\n', ...
    meanDist_D1);


fprintf( ...
    'Mean distance Day N: %.4f\n', ...
    meanDist_DN);


fprintf( ...
    'Distance ratio DN/D1: %.4f\n', ...
    distance_ratio);


%% =====================================================================
%% K. REAL WITHIN-CONDITION VARIABILITY
%% =====================================================================

radius_D1 = ...
    zeros(nVT,1);


radius_DN = ...
    zeros(nVT,1);


for i = 1:nVT

    radius_D1(i) = ...
        sqrt( ...
            trace(CovT1{i}) / ...
            N_PC);


    radius_DN(i) = ...
        sqrt( ...
            trace(CovTN_A{i}) / ...
            N_PC);

end


meanRadius_D1 = ...
    mean(radius_D1);


meanRadius_DN = ...
    mean(radius_DN);


radius_ratio = ...
    meanRadius_DN / ...
    max(meanRadius_D1,eps);


fprintf('\n============================================\n');
fprintf('Actual within-condition variability\n');
fprintf('============================================\n');


fprintf( ...
    'Mean radius Day 1: %.4f\n', ...
    meanRadius_D1);


fprintf( ...
    'Mean radius Day N: %.4f\n', ...
    meanRadius_DN);


fprintf( ...
    'Radius ratio DN/D1: %.4f\n', ...
    radius_ratio);


%% =====================================================================
%% L. REAL SEPARATION RELATIVE TO VARIABILITY
%% =====================================================================

normalized_sep_D1 = ...
    meanDist_D1 / ...
    max(meanRadius_D1,eps);


normalized_sep_DN = ...
    meanDist_DN / ...
    max(meanRadius_DN,eps);


normalized_sep_ratio = ...
    normalized_sep_DN / ...
    max(normalized_sep_D1,eps);


fprintf('\n============================================\n');
fprintf('Separation relative to variability\n');
fprintf('============================================\n');


fprintf( ...
    'Day 1: %.4f\n', ...
    normalized_sep_D1);


fprintf( ...
    'Day N: %.4f\n', ...
    normalized_sep_DN);


fprintf( ...
    'Ratio DN/D1: %.4f\n', ...
    normalized_sep_ratio);


%% =====================================================================
%% M. COMMON CONTROL NORMALIZATION SCALE
%% =====================================================================

control_radius_D1 = ...
    zeros(nVC,1);


control_radius_DN = ...
    zeros(nVC,1);


for i = 1:nVC

    control_radius_D1(i) = ...
        sqrt( ...
            trace(CovC1{i}) / ...
            N_PC);


    control_radius_DN(i) = ...
        sqrt( ...
            trace(CovCN_A{i}) / ...
            N_PC);

end


all_control_radius = ...
    [ ...
    control_radius_D1(:); ...
    control_radius_DN(:) ...
    ];


control_scale = ...
    median( ...
        all_control_radius, ...
        'omitnan');


if ~isfinite(control_scale) || ...
        control_scale <= eps

    error( ...
        'Invalid control normalization scale.');

end


fprintf('\n============================================\n');
fprintf('Common normalization\n');
fprintf('============================================\n');


fprintf( ...
    'Control scale: %.4f\n', ...
    control_scale);


%% =====================================================================
%% N. NORMALIZE CENTROIDS / COVARIANCES
%% =====================================================================

CenT1_norm = ...
    CenT1_raw ./ ...
    control_scale;


CenTN_norm = ...
    CenTN_A ./ ...
    control_scale;


CovT1_norm = ...
    cell(size(CovT1));


CovTN_norm = ...
    cell(size(CovTN_A));


for i = 1:nVT

    CovT1_norm{i} = ...
        CovT1{i} ./ ...
        (control_scale^2);


    CovTN_norm{i} = ...
        CovTN_A{i} ./ ...
        (control_scale^2);

end


%% =====================================================================
%% O. CENTER EACH DAY FOR VISUALIZATION ONLY
%% =====================================================================

visual_center_D1 = ...
    mean(CenT1_norm,1);


visual_center_DN = ...
    mean(CenTN_norm,1);


CenT1_plot = ...
    CenT1_norm - ...
    visual_center_D1;


CenTN_plot = ...
    CenTN_norm - ...
    visual_center_DN;


fprintf('\n============================================\n');
fprintf('Display centering\n');
fprintf('============================================\n');


fprintf( ...
    'Day 1 removed center: [%.3f %.3f %.3f]\n', ...
    visual_center_D1(1), ...
    visual_center_D1(2), ...
    visual_center_D1(3));


fprintf( ...
    'Day N removed center: [%.3f %.3f %.3f]\n', ...
    visual_center_DN(1), ...
    visual_center_DN(2), ...
    visual_center_DN(3));


%% =====================================================================
%% P. DISPLAY-ONLY VARIANCE MATCHING
%% =====================================================================

display_radius_D1 = ...
    zeros(nVT,1);


display_radius_DN = ...
    zeros(nVT,1);


for i = 1:nVT

    display_radius_D1(i) = ...
        sqrt( ...
            trace(CovT1_norm{i}) / ...
            N_PC);


    display_radius_DN(i) = ...
        sqrt( ...
            trace(CovTN_norm{i}) / ...
            N_PC);

end


mean_display_radius_D1 = ...
    mean(display_radius_D1);


mean_display_radius_DN = ...
    mean(display_radius_DN);


reference_radius = ...
    0.5 * ...
    ( ...
    mean_display_radius_D1 + ...
    mean_display_radius_DN ...
    );


display_cov_scale_D1 = ...
    ( ...
    reference_radius / ...
    max(mean_display_radius_D1,eps) ...
    )^2;


display_cov_scale_DN = ...
    ( ...
    reference_radius / ...
    max(mean_display_radius_DN,eps) ...
    )^2;


CovT1_plot = ...
    cell(size(CovT1_norm));


CovTN_plot = ...
    cell(size(CovTN_norm));


for i = 1:nVT

    CovT1_plot{i} = ...
        CovT1_norm{i} .* ...
        display_cov_scale_D1;


    CovTN_plot{i} = ...
        CovTN_norm{i} .* ...
        display_cov_scale_DN;

end


fprintf('\n============================================\n');
fprintf('Variance-matched display\n');
fprintf('============================================\n');


fprintf( ...
    'Original display radius Day 1: %.4f\n', ...
    mean_display_radius_D1);


fprintf( ...
    'Original display radius Day N: %.4f\n', ...
    mean_display_radius_DN);


fprintf( ...
    'Reference radius: %.4f\n', ...
    reference_radius);


fprintf( ...
    'Display covariance scale Day 1: %.4f\n', ...
    display_cov_scale_D1);


fprintf( ...
    'Display covariance scale Day N: %.4f\n', ...
    display_cov_scale_DN);


%% =====================================================================
%% Q. VERIFY DISPLAY MATCHING
%% =====================================================================

matched_radius_D1 = ...
    zeros(nVT,1);


matched_radius_DN = ...
    zeros(nVT,1);


for i = 1:nVT

    matched_radius_D1(i) = ...
        sqrt( ...
            trace(CovT1_plot{i}) / ...
            N_PC);


    matched_radius_DN(i) = ...
        sqrt( ...
            trace(CovTN_plot{i}) / ...
            N_PC);

end


fprintf( ...
    '\nMatched display radius Day 1: %.4f\n', ...
    mean(matched_radius_D1));


fprintf( ...
    'Matched display radius Day N: %.4f\n', ...
    mean(matched_radius_DN));


%% =====================================================================
%% R. COMMON SYMMETRIC AXIS LIMITS
%% =====================================================================

[xlim_raw,ylim_raw,zlim_raw] = ...
    get_common_tight_limits_3d( ...
        CenT1_plot, ...
        CovT1_plot, ...
        CenTN_plot, ...
        CovTN_plot, ...
        ELLIPSOID_STD_3D, ...
        AXIS_MARGIN);


x_extent = ...
    max(abs(xlim_raw));


y_extent = ...
    max(abs(ylim_raw));


z_extent = ...
    max(abs(zlim_raw));


xlim_common = ...
    [-x_extent x_extent];


ylim_common = ...
    [-y_extent y_extent];


zlim_common = ...
    [-z_extent z_extent];


fprintf('\n============================================\n');
fprintf('Display limits\n');
fprintf('============================================\n');


fprintf( ...
    'D1: [%.3f %.3f]\n', ...
    xlim_common(1), ...
    xlim_common(2));


fprintf( ...
    'D2: [%.3f %.3f]\n', ...
    ylim_common(1), ...
    ylim_common(2));


fprintf( ...
    'D3: [%.3f %.3f]\n', ...
    zlim_common(1), ...
    zlim_common(2));


%% =====================================================================
%% S. COLORS
%% =====================================================================

trained_map = [

    0.902 0.624 0.000;
    0.337 0.706 0.914;
    0.000 0.620 0.451;
    0.941 0.894 0.259;
    0.000 0.447 0.698;
    0.835 0.369 0.000;
    0.800 0.475 0.655;
    0.500 0.500 0.500;
    0.400 0.200 0.600;

    ];


if nVT > size(trained_map,1)

    error( ...
        'Not enough colors for %d conditions.', ...
        nVT);

end


trained_map = ...
    trained_map(1:nVT,:);


%% =====================================================================
%% T. CREATE FIGURE
%% =====================================================================

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[ ...
        2 ...
        2 ...
        FIG_W_CM ...
        FIG_H_CM ...
        ], ...
    'PaperUnits','centimeters', ...
    'PaperPosition',[ ...
        0 ...
        0 ...
        FIG_W_CM ...
        FIG_H_CM ...
        ], ...
    'PaperSize',[ ...
        FIG_W_CM ...
        FIG_H_CM ...
        ], ...
    'Renderer','opengl');


%% =====================================================================
%% U. TILED LAYOUT
%% =====================================================================

tl = tiledlayout( ...
    fig, ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% ---------------------------------------------------------------------
% Day 1
%% ---------------------------------------------------------------------

ax1 = nexttile(tl,1);


disableDefaultInteractivity(ax1);


try
    ax1.Toolbar.Visible = 'off';
catch
end


%% ---------------------------------------------------------------------
% Day N
%% ---------------------------------------------------------------------

ax2 = nexttile(tl,2);


disableDefaultInteractivity(ax2);


try
    ax2.Toolbar.Visible = 'off';
catch
end


%% =====================================================================
%% V. DRAW DAY 1
%% =====================================================================

draw_manifold_clean_axes( ...
    ax1, ...
    CenT1_plot, ...
    CovT1_plot, ...
    ELLIPSOID_STD_3D, ...
    trained_map, ...
    ALPHA_3D, ...
    ELLIPSOID_RES, ...
    xlim_common, ...
    ylim_common, ...
    zlim_common, ...
    FONT_NAME, ...
    FONT_AXIS, ...
    AXIS_LINE_WIDTH, ...
    VIEW_AZ, ...
    VIEW_EL);


%% =====================================================================
%% W. DRAW DAY N
%% =====================================================================

draw_manifold_clean_axes( ...
    ax2, ...
    CenTN_plot, ...
    CovTN_plot, ...
    ELLIPSOID_STD_3D, ...
    trained_map, ...
    ALPHA_3D, ...
    ELLIPSOID_RES, ...
    xlim_common, ...
    ylim_common, ...
    zlim_common, ...
    FONT_NAME, ...
    FONT_AXIS, ...
    AXIS_LINE_WIDTH, ...
    VIEW_AZ, ...
    VIEW_EL);


%% =====================================================================
%% X. PANEL TITLES
%% =====================================================================

title( ...
    ax1, ...
    'Trained Day 1', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_TITLE, ...
    'FontWeight','bold');


title( ...
    ax2, ...
    'Trained Day N', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_TITLE, ...
    'FontWeight','bold');


%% =====================================================================
%% Y. FORCE IDENTICAL VIEW
%% =====================================================================

for ax = [ax1 ax2]

    xlim(ax,xlim_common);
    ylim(ax,ylim_common);
    zlim(ax,zlim_common);

    view(ax,[VIEW_AZ VIEW_EL]);

    ax.Projection = 'orthographic';

end


%% =====================================================================
%% Z. SAVE SUMMARY
%% =====================================================================

summary = struct();


summary.Day1_file = ...
    file_D1;


summary.DayN_file = ...
    file_DN;


summary.nNeuron_D1 = ...
    nNeuron_D1;


summary.nNeuron_DN = ...
    nNeuron_DN;


summary.explained_D1 = ...
    expl_D1;


summary.explained_DN = ...
    expl_DN;


summary.CenT1 = ...
    CenT1_raw;


summary.CenTN_aligned = ...
    CenTN_A;


summary.CovT1 = ...
    CovT1;


summary.CovTN_aligned = ...
    CovTN_A;


summary.CenC1 = ...
    CenC1_raw;


summary.CenCN_aligned = ...
    CenCN_A;


summary.CovC1 = ...
    CovC1;


summary.CovCN_aligned = ...
    CovCN_A;


summary.align_error_before = ...
    align_error_before;


summary.align_error_after = ...
    align_error_after;


summary.meanDist_D1 = ...
    meanDist_D1;


summary.meanDist_DN = ...
    meanDist_DN;


summary.distance_ratio = ...
    distance_ratio;


summary.radius_D1 = ...
    radius_D1;


summary.radius_DN = ...
    radius_DN;


summary.meanRadius_D1 = ...
    meanRadius_D1;


summary.meanRadius_DN = ...
    meanRadius_DN;


summary.radius_ratio = ...
    radius_ratio;


summary.normalized_sep_D1 = ...
    normalized_sep_D1;


summary.normalized_sep_DN = ...
    normalized_sep_DN;


summary.normalized_sep_ratio = ...
    normalized_sep_ratio;


summary.control_scale = ...
    control_scale;


summary.visual_center_D1 = ...
    visual_center_D1;


summary.visual_center_DN = ...
    visual_center_DN;


summary.CenT1_plot = ...
    CenT1_plot;


summary.CenTN_plot = ...
    CenTN_plot;


summary.mean_display_radius_D1_before_matching = ...
    mean_display_radius_D1;


summary.mean_display_radius_DN_before_matching = ...
    mean_display_radius_DN;


summary.reference_display_radius = ...
    reference_radius;


summary.display_cov_scale_D1 = ...
    display_cov_scale_D1;


summary.display_cov_scale_DN = ...
    display_cov_scale_DN;


summary.CovT1_plot = ...
    CovT1_plot;


summary.CovTN_plot = ...
    CovTN_plot;


summary.matched_display_radius_D1 = ...
    matched_radius_D1;


summary.matched_display_radius_DN = ...
    matched_radius_DN;


summary.xlim_common = ...
    xlim_common;


summary.ylim_common = ...
    ylim_common;


summary.zlim_common = ...
    zlim_common;


save( ...
    fullfile( ...
        SAVE_DIR, ...
        'Manifold_FinalClean_summary.mat'), ...
    'summary');


%% =====================================================================
%% AA. EXPORT
%% =====================================================================

drawnow;


fprintf('\n============================================\n');
fprintf('Export\n');
fprintf('============================================\n');


%% ---------------------------------------------------------------------
% PDF
%% ---------------------------------------------------------------------

if EXPORT_PDF


    pdf_file = ...
        fullfile( ...
            SAVE_DIR, ...
            'Manifold_FinalClean_PNAS.pdf');


    tic;


    exportgraphics( ...
        fig, ...
        pdf_file, ...
        'ContentType','image', ...
        'Resolution',RASTER_DPI);


    fprintf( ...
        'PDF: %.2f sec\n', ...
        toc);

end


%% ---------------------------------------------------------------------
% PNG
%% ---------------------------------------------------------------------

if EXPORT_PNG


    png_file = ...
        fullfile( ...
            SAVE_DIR, ...
            'Manifold_FinalClean_PNAS.png');


    tic;


    exportgraphics( ...
        fig, ...
        png_file, ...
        'Resolution',RASTER_DPI);


    fprintf( ...
        'PNG: %.2f sec\n', ...
        toc);

end


%% ---------------------------------------------------------------------
% TIFF
%% ---------------------------------------------------------------------

if EXPORT_TIF


    tif_file = ...
        fullfile( ...
            SAVE_DIR, ...
            'Manifold_FinalClean_PNAS.tif');


    tic;


    exportgraphics( ...
        fig, ...
        tif_file, ...
        'Resolution',RASTER_DPI);


    fprintf( ...
        'TIFF: %.2f sec\n', ...
        toc);

end


fprintf('\nFinished.\n');


%% =====================================================================
%% LOCAL FUNCTION 1
%% EXTRACT CATEGORY DATA
%% =====================================================================

function dat = ...
    extract_category_data( ...
        S, ...
        category_name, ...
        target_indices)


idx_cat = ...
    find( ...
        strcmp( ...
            S.meta.category_names, ...
            category_name), ...
        1);


if isempty(idx_cat)

    error( ...
        'Category not found: %s', ...
        category_name);

end


raw = ...
    S.FR_by_category{idx_cat};


if max(target_indices) > size(raw,2)

    error( ...
        ['Target index %d exceeds available ' ...
         'target dimension (%d).'], ...
        max(target_indices), ...
        size(raw,2));

end


dat = ...
    raw(:,target_indices,:);

end


%% =====================================================================
%% LOCAL FUNCTION 2
%% FIT PCA
%% =====================================================================

function [mu,sd_v,coeff,explained] = ...
    fit_day_pca( ...
        trained_data, ...
        control_data, ...
        N_PC)


XT = ...
    tensor_to_observations( ...
        trained_data);


XC = ...
    tensor_to_observations( ...
        control_data);


X = ...
    [XT;XC];


mu = ...
    mean( ...
        X, ...
        1, ...
        'omitnan');


sd_v = ...
    std( ...
        X, ...
        0, ...
        1, ...
        'omitnan');


sd_v(sd_v < eps) = ...
    1;


Xz = ...
    (X-mu) ./ ...
    sd_v;


Xz(~isfinite(Xz)) = ...
    0;


[coeff,~,~,~,explained] = ...
    pca(Xz);


if size(coeff,2) < N_PC

    error( ...
        'Only %d PCs available; requested %d.', ...
        size(coeff,2), ...
        N_PC);

end

end


%% =====================================================================
%% LOCAL FUNCTION 3
%% PROJECT DATA
%% =====================================================================

function [P,nCondition,nRep] = ...
    project_tensor( ...
        dat, ...
        mu, ...
        sd_v, ...
        coeff, ...
        N_PC)


nCondition = ...
    size(dat,2);


nRep = ...
    size(dat,3);


X = ...
    tensor_to_observations(dat);


Xz = ...
    (X-mu) ./ ...
    sd_v;


Xz(~isfinite(Xz)) = ...
    0;


P = ...
    Xz * ...
    coeff(:,1:N_PC);

end


%% =====================================================================
%% LOCAL FUNCTION 4
%% TENSOR -> OBSERVATION MATRIX
%% =====================================================================

function X = ...
    tensor_to_observations(dat)


nNeuron = ...
    size(dat,1);


nCondition = ...
    size(dat,2);


nRep = ...
    size(dat,3);


tmp = ...
    permute( ...
        dat, ...
        [2 3 1]);


X = ...
    reshape( ...
        tmp, ...
        nCondition*nRep, ...
        nNeuron);

end


%% =====================================================================
%% LOCAL FUNCTION 5
%% GET MANIFOLD STATISTICS
%% =====================================================================

function [Cs,Vs] = ...
    get_manifold_stats( ...
        P, ...
        nCondition, ...
        nRep)


nDim = ...
    size(P,2);


expected_rows = ...
    nCondition*nRep;


if size(P,1) ~= expected_rows

    error( ...
        ['Projected observations = %d, expected %d ' ...
         '(%d conditions x %d repetitions).'], ...
        size(P,1), ...
        expected_rows, ...
        nCondition, ...
        nRep);

end


Cs = ...
    nan( ...
        nCondition, ...
        nDim);


Vs = ...
    cell( ...
        1, ...
        nCondition);


for i = 1:nCondition


    idx_start = ...
        (i-1)*nRep + 1;


    idx_end = ...
        i*nRep;


    Pi = ...
        P(idx_start:idx_end,:);


    Cs(i,:) = ...
        mean( ...
            Pi, ...
            1, ...
            'omitnan');


    if size(Pi,1) < 2


        Vs{i} = ...
            eye(nDim)*1e-6;


    else


        C = ...
            cov( ...
                Pi, ...
                'omitrows');


        if isempty(C) || ...
                any(~isfinite(C(:)))


            C = ...
                eye(nDim)*1e-6;


        end


        Vs{i} = ...
            regularize_cov(C);


    end

end

end


%% =====================================================================
%% LOCAL FUNCTION 6
%% DRAW CLEAN 3-D MANIFOLD WITH TRUE AXIS LABELS
%% =====================================================================

function draw_manifold_clean_axes( ...
    ax, ...
    Cs, ...
    Vs, ...
    sd_scale, ...
    colors, ...
    alpha_val, ...
    sphere_res, ...
    x_lim, ...
    y_lim, ...
    z_lim, ...
    font_name, ...
    font_axis, ...
    axis_line_width, ...
    view_az, ...
    view_el)


hold(ax,'on');


%% ---------------------------------------------------------------------
% Sphere template
%% ---------------------------------------------------------------------

[sx,sy,sz] = ...
    sphere(sphere_res);


%% ---------------------------------------------------------------------
% Draw ellipsoids
%% ---------------------------------------------------------------------

for i = 1:size(Cs,1)


    C = ...
        regularize_cov( ...
            Vs{i});


    [V,D] = ...
        eig_sorted(C);


    r = ...
        sd_scale .* ...
        sqrt( ...
            max( ...
                diag(D), ...
                0));


    xyz = ...
        [ ...
        sx(:)*r(1), ...
        sy(:)*r(2), ...
        sz(:)*r(3) ...
        ] * V';


    ex = ...
        reshape( ...
            xyz(:,1)+Cs(i,1), ...
            size(sx));


    ey = ...
        reshape( ...
            xyz(:,2)+Cs(i,2), ...
            size(sy));


    ez = ...
        reshape( ...
            xyz(:,3)+Cs(i,3), ...
            size(sz));


    surf( ...
        ax, ...
        ex, ...
        ey, ...
        ez, ...
        'FaceColor',colors(i,:), ...
        'FaceAlpha',alpha_val, ...
        'EdgeColor','none', ...
        'FaceLighting','gouraud', ...
        'AmbientStrength',0.68, ...
        'DiffuseStrength',0.72, ...
        'SpecularStrength',0.025);


    plot3( ...
        ax, ...
        Cs(i,1), ...
        Cs(i,2), ...
        Cs(i,3), ...
        'o', ...
        'MarkerSize',4.5, ...
        'MarkerFaceColor',colors(i,:), ...
        'MarkerEdgeColor',[ ...
            0.12 ...
            0.12 ...
            0.12 ...
            ], ...
        'LineWidth',0.45);

end


%% =====================================================================
%% LIMITS
%% =====================================================================

xlim(ax,x_lim);
ylim(ax,y_lim);
zlim(ax,z_lim);


%% =====================================================================
%% REMOVE NUMERIC TICKS
%% =====================================================================

ax.XTick = [];
ax.YTick = [];
ax.ZTick = [];


%% =====================================================================
%% TRUE AXIS LABELS
%
% Important:
% Do not modify Position.
%% =====================================================================

xlabel( ...
    ax, ...
    'D1', ...
    'FontName',font_name, ...
    'FontSize',font_axis, ...
    'FontWeight','normal');


ylabel( ...
    ax, ...
    'D2', ...
    'FontName',font_name, ...
    'FontSize',font_axis, ...
    'FontWeight','normal');


zlabel( ...
    ax, ...
    'D3', ...
    'FontName',font_name, ...
    'FontSize',font_axis, ...
    'FontWeight','normal');


%% =====================================================================
%% AXIS STYLE
%% =====================================================================

ax.FontName = ...
    font_name;


ax.LineWidth = ...
    axis_line_width;


ax.XColor = ...
    [0.18 0.18 0.18];


ax.YColor = ...
    [0.18 0.18 0.18];


ax.ZColor = ...
    [0.18 0.18 0.18];


ax.Color = ...
    'w';


grid(ax,'off');

box(ax,'off');


%% =====================================================================
%% CAMERA
%% =====================================================================

view( ...
    ax, ...
    [ ...
    view_az ...
    view_el ...
    ]);


ax.Projection = ...
    'orthographic';


%% =====================================================================
%% LIGHTING
%% =====================================================================

delete( ...
    findall( ...
        ax, ...
        'Type','light'));


light( ...
    ax, ...
    'Style','infinite', ...
    'Position',[ ...
        cosd(view_az) ...
        sind(view_az) ...
        0.8 ...
        ], ...
    'Color',[1 1 1]);


lighting(ax,'gouraud');


hold(ax,'off');

end


%% =====================================================================
%% LOCAL FUNCTION 7
%% COMMON TIGHT LIMITS
%% =====================================================================

function [x_lim,y_lim,z_lim] = ...
    get_common_tight_limits_3d( ...
        Cs1, ...
        Vs1, ...
        Cs2, ...
        Vs2, ...
        sd_scale, ...
        margin_fraction)


all_min = ...
    [inf inf inf];


all_max = ...
    [-inf -inf -inf];


%% ---------------------------------------------------------------------
% Dataset 1
%% ---------------------------------------------------------------------

for i = 1:size(Cs1,1)


    C = ...
        regularize_cov( ...
            Vs1{i});


    extent = ...
        sd_scale .* ...
        sqrt( ...
            max( ...
                diag(C), ...
                0))';


    low = ...
        Cs1(i,:) - ...
        extent;


    high = ...
        Cs1(i,:) + ...
        extent;


    all_min = ...
        min( ...
            all_min, ...
            low);


    all_max = ...
        max( ...
            all_max, ...
            high);

end


%% ---------------------------------------------------------------------
% Dataset 2
%% ---------------------------------------------------------------------

for i = 1:size(Cs2,1)


    C = ...
        regularize_cov( ...
            Vs2{i});


    extent = ...
        sd_scale .* ...
        sqrt( ...
            max( ...
                diag(C), ...
                0))';


    low = ...
        Cs2(i,:) - ...
        extent;


    high = ...
        Cs2(i,:) + ...
        extent;


    all_min = ...
        min( ...
            all_min, ...
            low);


    all_max = ...
        max( ...
            all_max, ...
            high);

end


%% ---------------------------------------------------------------------
% Padding
%% ---------------------------------------------------------------------

range_xyz = ...
    all_max - ...
    all_min;


range_xyz( ...
    range_xyz < 1e-8) = ...
    1;


pad = ...
    range_xyz .* ...
    margin_fraction;


all_min = ...
    all_min - ...
    pad;


all_max = ...
    all_max + ...
    pad;


x_lim = ...
    [ ...
    all_min(1) ...
    all_max(1) ...
    ];


y_lim = ...
    [ ...
    all_min(2) ...
    all_max(2) ...
    ];


z_lim = ...
    [ ...
    all_min(3) ...
    all_max(3) ...
    ];

end


%% =====================================================================
%% LOCAL FUNCTION 8
%% REGULARIZE COVARIANCE
%% =====================================================================

function C = ...
    regularize_cov(C)


C = ...
    (C+C')/2;


[V,D] = ...
    eig(C);


d = ...
    diag(D);


d(d < 1e-8) = ...
    1e-8;


C = ...
    V * ...
    diag(d) * ...
    V';


C = ...
    (C+C')/2;

end


%% =====================================================================
%% LOCAL FUNCTION 9
%% SORT EIGENVALUES
%% =====================================================================

function [V,D] = ...
    eig_sorted(C)


[V,D0] = ...
    eig(C);


[d,idx] = ...
    sort( ...
        diag(D0), ...
        'descend');


V = ...
    V(:,idx);


D = ...
    diag(d);

end