%% =====================================================================
%  Analyze_Decomposition_D_VAR_PNAS_Subpanel.m
%
%  PNAS-style subpanel:
%  SDI / SVM Improvement (DiD vs Day 1)
%
%  Features:
%    1. Suitable as a panel in the main figure.
%    2. M1/L is blue; M2/G is red.
%    3. SDI uses solid colors; SVM uses lighter versions of the same colors.
%    4. Retain significance stars from the one-sample t test.
%    5. Remove the large title and reduce whitespace and font sizes.
%    6. Export vector PDF and 600 dpi TIFF/PNG.
%% =====================================================================

clear; clc; close all;

%% =====================================================================
%% A. Define groups and category settings
%% =====================================================================

DATA_PARENT_DIRECTORY = ...
    figure_input('fig2');

analysis_groups = {'L', 'G'};

group_sessions = struct();

group_sessions.L = {'s1', 'extra_var', 's2'};
group_sessions.G = {'s3', 's5'};

session_T_categories = struct();

session_T_categories.s1 = {'T1', 'T2'};
session_T_categories.extra_var = {'T1', 'T2'};
session_T_categories.s2 = {'T1', 'T2'};
session_T_categories.s3 = {'T1', 'T2'};
session_T_categories.s5 = {'T1', 'T2', 'T3', 'T4'};

session_U_categories = struct();

session_U_categories.s1 = {'U1', 'U2'};
session_U_categories.extra_var = {'U1', 'U2'};
session_U_categories.s2 = {'U1', 'U2'};
session_U_categories.s3 = {'U1', 'U2'};
session_U_categories.s5 = {'U1', 'U2', 'U3', 'U4'};

session_config = struct();

session_config.s1.trained_ids = [7;8;9;12;13;14;17;18;19];
session_config.extra_var.trained_ids = [7;8;9;12;13;14;17;18;19];
session_config.s5.trained_ids = [7;8;9;12;13;14;17;18;19];

session_config.s2.trained_ids = [3;11;12;13;21];

session_config.s3.trained_ids = [10:18];

% ---------------------------------------------------------
% Explicit post-training indices
% ---------------------------------------------------------

session_post_indices = struct();

session_post_indices.s1 = [3,4,5,6];
session_post_indices.s2 = [2,3];
session_post_indices.s3 = [2,3];
session_post_indices.s5 = [3,4,5,6];

% ---------------------------------------------------------
% DiD storage containers
% ---------------------------------------------------------

GROUP_DID_POOL_SDI_RAW = struct('L', [], 'G', []);
GROUP_DID_POOL_SVM     = struct('L', [], 'G', []);

%% =====================================================================
%% A.1 PNAS-style colors and fonts
%% =====================================================================

% M1 / L = blue
color_L = [0.20, 0.40, 0.80];

% M2 / G = red
color_G = [0.85, 0.30, 0.30];

% ---------------------------------------------------------
% Use a lighter version of the same color for SVM.
% ---------------------------------------------------------

color_L_light = ...
    0.55 * color_L + ...
    0.45 * [1 1 1];

color_G_light = ...
    0.55 * color_G + ...
    0.45 * [1 1 1];

FONT_NAME = 'Arial';

% ---------------------------------------------------------
% Keep the PNAS subpanel compact.
% ---------------------------------------------------------

FONT_TICK   = 8;
FONT_LABEL  = 9;
FONT_LEGEND = 8;
FONT_STAR   = 10;
FONT_PANEL  = 12;

%% =====================================================================
%% B. Loop 1: load SDI data
%% =====================================================================

fprintf('\n--- (1) LOADING SDI DATA ---\n');

for group_idx = 1:length(analysis_groups)

    current_group = analysis_groups{group_idx};

    current_sessions_in_group = ...
        group_sessions.(current_group);

    SDI_directory = fullfile( ...
        DATA_PARENT_DIRECTORY, ...
        'Results_SDI', ...
        current_group);

    mat_files = dir(fullfile( ...
        SDI_directory, ...
        'SDI_Results_FR_*.mat'));

    if isempty(mat_files)
        continue;
    end

    file_info = parse_files( ...
        mat_files, ...
        SDI_directory, ...
        current_sessions_in_group);

    if isempty(file_info)
        continue;
    end

    sessions = unique({file_info.session});

    for s_idx = 1:length(sessions)

        session_name = sessions{s_idx};

        session_mask = ...
            strcmp({file_info.session},session_name);

        session_files = ...
            file_info(session_mask);

        [~,sort_idx] = ...
            sort([session_files.datenum]);

        session_files = ...
            session_files(sort_idx);

        n_days = length(session_files);

        if n_days < 2
            continue;
        end

        T_cats = ...
            session_T_categories.(session_name);

        U_cats = ...
            session_U_categories.(session_name);

        trained_ids = ...
            session_config.(session_name).trained_ids;

        day_data_sdi = struct();

        all_cats = [T_cats,U_cats];

        for day_idx = 1:n_days

            data = load( ...
                session_files(day_idx).path, ...
                'SDI_results');

            for cat_idx = 1:length(all_cats)

                cat_name = all_cats{cat_idx};

                if ~isfield(day_data_sdi,cat_name)

                    day_data_sdi.(cat_name) = ...
                        nan(1,n_days);

                end

                if isfield(data.SDI_results,cat_name)

                    VALUE_matrix = ...
                        data.SDI_results.(cat_name).SDI_matrix;

                    values = ...
                        extract_pair_values( ...
                        VALUE_matrix, ...
                        trained_ids);

                    day_data_sdi.(cat_name)(day_idx) = ...
                        mean(values,'omitnan');

                end

            end

        end

        if isfield( ...
                session_post_indices, ...
                session_name)

            post_indices = ...
                session_post_indices.(session_name);

        else
            continue;
        end

        for day_idx = post_indices

            if day_idx > n_days
                continue;
            end

            [ ...
                mean_change_T, ...
                mean_change_U, ...
                base_T_sdi, ...
                base_U_sdi ...
                ] = ...
                calculate_changes( ...
                day_data_sdi, ...
                T_cats, ...
                U_cats, ...
                day_idx);

            if ~isnan(mean_change_T)

                pct_T = ...
                    (mean_change_T/base_T_sdi)*100;

                pct_U = ...
                    (mean_change_U/base_U_sdi)*100;

                GROUP_DID_POOL_SDI_RAW.(current_group) = ...
                    [ ...
                    GROUP_DID_POOL_SDI_RAW.(current_group); ...
                    pct_T-pct_U ...
                    ];

            end

        end

    end

end

%% =====================================================================
%% C. Loop 2: load SVM data
%% =====================================================================

fprintf('\n--- (2) LOADING SVM DATA ---\n');

for group_idx = 1:length(analysis_groups)

    current_group = analysis_groups{group_idx};

    current_sessions_in_group = ...
        group_sessions.(current_group);

    SVM_directory = fullfile( ...
        DATA_PARENT_DIRECTORY, ...
        'Results_SVM', ...
        current_group);

    mat_files = dir(fullfile( ...
        SVM_directory, ...
        'SVM_Results_FR_*.mat'));

    if isempty(mat_files)
        continue;
    end

    file_info = parse_files( ...
        mat_files, ...
        SVM_directory, ...
        current_sessions_in_group);

    if isempty(file_info)
        continue;
    end

    sessions = ...
        unique({file_info.session});

    for s_idx = 1:length(sessions)

        session_name = ...
            sessions{s_idx};

        session_mask = ...
            strcmp({file_info.session},session_name);

        session_files = ...
            file_info(session_mask);

        [~,sort_idx] = ...
            sort([session_files.datenum]);

        session_files = ...
            session_files(sort_idx);

        n_days = ...
            length(session_files);

        if n_days < 2
            continue;
        end

        T_cats = ...
            session_T_categories.(session_name);

        U_cats = ...
            session_U_categories.(session_name);

        trained_ids = ...
            session_config.(session_name).trained_ids;

        day_data_svm = struct();

        all_cats = [T_cats,U_cats];

        for day_idx = 1:n_days

            data = load( ...
                session_files(day_idx).path, ...
                'SVM_results');

            for cat_idx = 1:length(all_cats)

                cat_name = ...
                    all_cats{cat_idx};

                if ~isfield(day_data_svm,cat_name)

                    day_data_svm.(cat_name) = ...
                        nan(1,n_days);

                end

                if isfield(data.SVM_results,cat_name)

                    VALUE_matrix = ...
                        data.SVM_results.(cat_name).SVM_matrix;

                    values = ...
                        extract_pair_values( ...
                        VALUE_matrix, ...
                        trained_ids);

                    day_data_svm.(cat_name)(day_idx) = ...
                        mean(values,'omitnan');

                end

            end

        end

        if isfield( ...
                session_post_indices, ...
                session_name)

            post_indices = ...
                session_post_indices.(session_name);

        else
            continue;
        end

        for day_idx = post_indices

            if day_idx > n_days
                continue;
            end

            [ ...
                mean_change_T, ...
                mean_change_U, ...
                base_T_svm, ...
                base_U_svm ...
                ] = ...
                calculate_changes( ...
                day_data_svm, ...
                T_cats, ...
                U_cats, ...
                day_idx);

            if ~isnan(mean_change_T)

                pct_T = ...
                    (mean_change_T/base_T_svm)*100;

                pct_U = ...
                    (mean_change_U/base_U_svm)*100;

                GROUP_DID_POOL_SVM.(current_group) = ...
                    [ ...
                    GROUP_DID_POOL_SVM.(current_group); ...
                    pct_T-pct_U ...
                    ];

            end

        end

    end

end

%% =====================================================================
%% D. Statistical analysis
%% =====================================================================

fprintf('\n\n========================================\n');
fprintf('FINAL STATISTICAL ANALYSIS (T-TEST)\n');
fprintf('========================================\n');

SDI_M1_pct = GROUP_DID_POOL_SDI_RAW.L;
SDI_M2_pct = GROUP_DID_POOL_SDI_RAW.G;

SVM_M1_pct = GROUP_DID_POOL_SVM.L;
SVM_M2_pct = GROUP_DID_POOL_SVM.G;

% ---------------------------------------------------------
% Compute the effective N separately for each array.
% This avoids assigning SDI's sample size to SVM.
% ---------------------------------------------------------

N_SDI_M1 = sum(~isnan(SDI_M1_pct));
N_SDI_M2 = sum(~isnan(SDI_M2_pct));

N_SVM_M1 = sum(~isnan(SVM_M1_pct));
N_SVM_M2 = sum(~isnan(SVM_M2_pct));

Means_SDI = [
    mean(SDI_M1_pct,'omitnan'), ...
    mean(SDI_M2_pct,'omitnan')
    ];

SEMs_SDI = [
    std(SDI_M1_pct,'omitnan')/sqrt(max(N_SDI_M1,1)), ...
    std(SDI_M2_pct,'omitnan')/sqrt(max(N_SDI_M2,1))
    ];

Means_SVM = [
    mean(SVM_M1_pct,'omitnan'), ...
    mean(SVM_M2_pct,'omitnan')
    ];

SEMs_SVM = [
    std(SVM_M1_pct,'omitnan')/sqrt(max(N_SVM_M1,1)), ...
    std(SVM_M2_pct,'omitnan')/sqrt(max(N_SVM_M2,1))
    ];

Stats = struct();

Data_Pct = {
    SDI_M1_pct, ...
    SDI_M2_pct, ...
    SVM_M1_pct, ...
    SVM_M2_pct
    };

Labels = {
    'SDI_M1', ...
    'SDI_M2', ...
    'SVM_M1', ...
    'SVM_M2'
    };

fprintf('\n--- Statistics (One-Sample T-Test vs 0, %% Improvement) ---\n');

for i = 1:length(Data_Pct)

    valid_data = ...
        Data_Pct{i}(~isnan(Data_Pct{i}));

    if numel(valid_data) >= 2

        [~,p,~,stats] = ...
            ttest(valid_data,0);

        Stats.(Labels{i}).p = p;
        Stats.(Labels{i}).stat_val = stats.tstat;

    else

        Stats.(Labels{i}).p = NaN;
        Stats.(Labels{i}).stat_val = NaN;

    end

    Mean_current = ...
        mean(valid_data,'omitnan');

    fprintf( ...
        '%s (N=%d): Mean=%.2f%%, T-Stat=%.3f, p=%.4f\n', ...
        Labels{i}, ...
        numel(valid_data), ...
        Mean_current, ...
        Stats.(Labels{i}).stat_val, ...
        Stats.(Labels{i}).p);

end

%% =====================================================================
%% E. PNAS-style subpanel
%% =====================================================================

% =========================================================
% Single-panel dimensions:
% Approximately 8.5 cm wide by 7.0 cm high.
%
% Suitable for assembly as a panel in Affinity.
% =========================================================

FIG_W_CM = 8.6;
FIG_H_CM = 7.0;

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2,2,FIG_W_CM,FIG_H_CM], ...
    'PaperUnits','centimeters', ...
    'PaperPosition',[0,0,FIG_W_CM,FIG_H_CM], ...
    'PaperSize',[FIG_W_CM,FIG_H_CM]);

% ---------------------------------------------------------
% Leave room for the y-axis label and the legend above.
% ---------------------------------------------------------

ax1 = axes( ...
    'Position',[0.18,0.18,0.76,0.66]);

hold(ax1,'on');

% =========================================================
% positions
% =========================================================

group_x = [1,2];

offset = 0.18;

bar_width = 0.28;

x_sdi = ...
    group_x-offset;

x_svm = ...
    group_x+offset;

% =========================================================
% zero line
% =========================================================

yline( ...
    ax1, ...
    0, ...
    '--', ...
    'Color',[0.55,0.55,0.55], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

% =========================================================
% Bars
%
% SDI = full color
% SVM = light color
% =========================================================

b1 = bar( ...
    ax1, ...
    x_sdi(1), ...
    Means_SDI(1), ...
    bar_width, ...
    'FaceColor',color_L, ...
    'EdgeColor','none');

b2 = bar( ...
    ax1, ...
    x_svm(1), ...
    Means_SVM(1), ...
    bar_width, ...
    'FaceColor',color_L_light, ...
    'EdgeColor','none');

b3 = bar( ...
    ax1, ...
    x_sdi(2), ...
    Means_SDI(2), ...
    bar_width, ...
    'FaceColor',color_G, ...
    'EdgeColor','none');

b4 = bar( ...
    ax1, ...
    x_svm(2), ...
    Means_SVM(2), ...
    bar_width, ...
    'FaceColor',color_G_light, ...
    'EdgeColor','none');

% =========================================================
% Error bars
% =========================================================

errorbar( ...
    ax1, ...
    x_sdi(1), ...
    Means_SDI(1), ...
    SEMs_SDI(1), ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.0, ...
    'CapSize',5);

errorbar( ...
    ax1, ...
    x_svm(1), ...
    Means_SVM(1), ...
    SEMs_SVM(1), ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.0, ...
    'CapSize',5);

errorbar( ...
    ax1, ...
    x_sdi(2), ...
    Means_SDI(2), ...
    SEMs_SDI(2), ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.0, ...
    'CapSize',5);

errorbar( ...
    ax1, ...
    x_svm(2), ...
    Means_SVM(2), ...
    SEMs_SVM(2), ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.0, ...
    'CapSize',5);

%% =====================================================================
%% F. Y-axis
%% =====================================================================

all_means = [
    Means_SDI, ...
    Means_SVM
    ];

all_sems = [
    SEMs_SDI, ...
    SEMs_SVM
    ];

global_max = ...
    max(all_means+all_sems,[],'omitnan');

global_min = ...
    min(all_means-all_sems,[],'omitnan');

% ---------------------------------------------------------
% Leave space for significance stars.
% ---------------------------------------------------------

range_val = ...
    max(global_max-global_min,10);

padding_top = ...
    0.22*range_val;

padding_bottom = ...
    0.12*range_val;

y_top = ...
    global_max+padding_top;

y_bottom = ...
    min(global_min-padding_bottom,-5);

ylim(ax1,[y_bottom,y_top]);

%% =====================================================================
%% G. Significance stars
%% =====================================================================

star_offset = ...
    0.035*(y_top-y_bottom);

plot_significance_single( ...
    ax1, ...
    x_sdi(1), ...
    Means_SDI(1)+SEMs_SDI(1)+star_offset, ...
    Stats.SDI_M1.p, ...
    FONT_STAR);

plot_significance_single( ...
    ax1, ...
    x_svm(1), ...
    Means_SVM(1)+SEMs_SVM(1)+star_offset, ...
    Stats.SVM_M1.p, ...
    FONT_STAR);

plot_significance_single( ...
    ax1, ...
    x_sdi(2), ...
    Means_SDI(2)+SEMs_SDI(2)+star_offset, ...
    Stats.SDI_M2.p, ...
    FONT_STAR);

plot_significance_single( ...
    ax1, ...
    x_svm(2), ...
    Means_SVM(2)+SEMs_SVM(2)+star_offset, ...
    Stats.SVM_M2.p, ...
    FONT_STAR);

%% =====================================================================
%% H. Axis style
%% =====================================================================

set( ...
    ax1, ...
    'XTick',group_x, ...
    'XTickLabel',{'M1','M2'}, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_TICK, ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'TickLength',[0.02 0.02], ...
    'XColor',[0.08 0.08 0.08], ...
    'YColor',[0.08 0.08 0.08], ...
    'Box','off');

xlim(ax1,[0.55,2.45]);

ylabel( ...
    ax1, ...
    'DiD improvement (%)', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_LABEL, ...
    'FontWeight','normal');

% ---------------------------------------------------------
% The Animal Group label can be omitted in a subpanel.
% M1 and M2 already identify the groups.
% ---------------------------------------------------------

xlabel(ax1,'');

grid(ax1,'off');

%% =====================================================================
%% I. Legend
%% =====================================================================

% =========================================================
% The legend only identifies SDI and SVM.
% Separate M1 SDI/M1 SVM/M2 SDI/M2 SVM legend entries are unnecessary.
%
% Colors already identify M1 and M2.
% =========================================================

dummy_sdi = bar( ...
    ax1, ...
    NaN,NaN, ...
    bar_width, ...
    'FaceColor',[0.45 0.45 0.45], ...
    'EdgeColor','none');

dummy_svm = bar( ...
    ax1, ...
    NaN,NaN, ...
    bar_width, ...
    'FaceColor',[0.75 0.75 0.75], ...
    'EdgeColor','none');

lgd = legend( ...
    ax1, ...
    [dummy_sdi,dummy_svm], ...
    {'SDI','SVM'}, ...
    'Location','northoutside', ...
    'Orientation','horizontal', ...
    'Box','off');

lgd.FontName = FONT_NAME;
lgd.FontSize = FONT_LEGEND;

%% =====================================================================
%% J. Optional panel letter
%% =====================================================================

% ---------------------------------------------------------
% If panel letters are added separately in Affinity,
% this block can be commented out.
% ---------------------------------------------------------

annotation( ...
    fig, ...
    'textbox', ...
    [0.015,0.92,0.05,0.05], ...
    'String','E', ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_PANEL, ...
    'FontWeight','bold', ...
    'LineStyle','none', ...
    'Margin',0);

%% =====================================================================
%% K. Export
%% =====================================================================

exportgraphics( ...
    fig, ...
    'SDI_SVM_Improvement_PNAS_Subpanel.pdf', ...
    'ContentType','vector');

exportgraphics( ...
    fig, ...
    'SDI_SVM_Improvement_PNAS_Subpanel.png', ...
    'Resolution',600);

exportgraphics( ...
    fig, ...
    'SDI_SVM_Improvement_PNAS_Subpanel.tif', ...
    'Resolution',600);

fprintf('\nSaved:\n');
fprintf('SDI_SVM_Improvement_PNAS_Subpanel.pdf\n');
fprintf('SDI_SVM_Improvement_PNAS_Subpanel.png\n');
fprintf('SDI_SVM_Improvement_PNAS_Subpanel.tif\n');

%% =====================================================================
%% HELPER FUNCTIONS
%% =====================================================================

function [ ...
    mean_change_T, ...
    mean_change_U, ...
    mean_baseline_T, ...
    mean_baseline_U ...
    ] = ...
    calculate_changes( ...
    day_data_T, ...
    T_cats, ...
    U_cats, ...
    day_idx, ...
    day_data_U)

    if nargin < 5
        day_data_U = day_data_T;
    end

    changes_T = [];
    changes_U = [];

    baseline_T = [];
    baseline_U = [];

    for i = 1:length(T_cats)

        cat_name = T_cats{i};

        if isfield(day_data_T,cat_name)

            change = ...
                day_data_T.(cat_name)(day_idx) - ...
                day_data_T.(cat_name)(1);

            changes_T = ...
                [changes_T;change];

            baseline_T = ...
                [baseline_T;day_data_T.(cat_name)(1)];

        end

    end

    for i = 1:length(U_cats)

        cat_name = U_cats{i};

        if isfield(day_data_U,cat_name)

            change = ...
                day_data_U.(cat_name)(day_idx) - ...
                day_data_U.(cat_name)(1);

            changes_U = ...
                [changes_U;change];

            baseline_U = ...
                [baseline_U;day_data_U.(cat_name)(1)];

        end

    end

    mean_change_T = ...
        mean(changes_T,'omitnan');

    mean_change_U = ...
        mean(changes_U,'omitnan');

    mean_baseline_T = ...
        mean(baseline_T,'omitnan');

    mean_baseline_U = ...
        mean(baseline_U,'omitnan');

end

%% =====================================================================

function file_info = ...
    parse_files( ...
    mat_files, ...
    directory, ...
    sessions_in_group)

    file_info = struct( ...
        'name',{}, ...
        'path',{}, ...
        'session',{}, ...
        'date',{}, ...
        'datenum',{});

    for f_idx = 1:numel(mat_files)

        fileName = ...
            mat_files(f_idx).name;

        filePath = ...
            fullfile(directory,fileName);

        session_match = ...
            regexp( ...
            fileName, ...
            's(\d+)', ...
            'tokens');

        if isempty(session_match)
            continue;
        end

        session_name = ...
            sprintf( ...
            's%d', ...
            str2double(session_match{1}{1}));

        if ~ismember( ...
                session_name, ...
                sessions_in_group)

            continue;

        end

        date_match = ...
            regexp( ...
            fileName, ...
            '(\d{6})\.mat$', ...
            'tokens');

        if isempty(date_match)
            continue;
        end

        date_str = ...
            date_match{1}{1};

        year = ...
            2000 + ...
            str2double(date_str(5:6));

        file_info(end+1).name = ...
            fileName;

        file_info(end).path = ...
            filePath;

        file_info(end).session = ...
            session_name;

        file_info(end).date = ...
            datetime( ...
            year, ...
            str2double(date_str(1:2)), ...
            str2double(date_str(3:4)));

        file_info(end).datenum = ...
            datenum(file_info(end).date);

    end

end

%% =====================================================================

function values = ...
    extract_pair_values( ...
    VALUE_matrix, ...
    ids)

    values = [];

    ids = ids(:);

    if isempty(ids)
        return;
    end

    pairs = ...
        nchoosek(ids,2);

    for k = 1:size(pairs,1)

        val = ...
            VALUE_matrix( ...
            pairs(k,1), ...
            pairs(k,2));

        if ~isnan(val)

            values = ...
                [values;val];

        end

    end

end

%% =====================================================================

function plot_significance_single( ...
    ax, ...
    x_pos, ...
    y_pos, ...
    p_val, ...
    font_size)

    if isnan(p_val)

        sig_label = '';

    elseif p_val < 0.001

        sig_label = '***';

    elseif p_val < 0.01

        sig_label = '**';

    elseif p_val < 0.05

        sig_label = '*';

    else

        sig_label = '';

    end

    if ~isempty(sig_label)

        text( ...
            ax, ...
            x_pos, ...
            y_pos, ...
            sig_label, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontName','Arial', ...
            'FontSize',font_size, ...
            'FontWeight','bold', ...
            'Interpreter','none');

    end

end